[package]
name = "xgrammar"
version = "0.3.2"
authors = ["Hyunsik Choi <hyunsik@furiosa.ai>"]
description = "Rust bindings for XGrammar"
edition = "2024"
license = "Apache-2.0"

exclude = [".github/*"]

[features]
default = ["hf_hub"]
hf_hub = ["dep:hf-hub"]
auto-init = []

[dependencies]
cpp = "0.5.10"
dlpark = { version = "0.6.0", features = ["ndarray"] }
globset = "0.4.16"
hf-hub = { version = "0.4.3", default-features = false, features = ["ureq"], optional = true }
libc = "0.2"
serde_json = "1"
tempfile = "3.20.0"
thiserror = "2"
tokenizers = { version = "0.21.2" }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[build-dependencies]
bindgen = "0.72.0"
cmake = "0.1.54"
cpp_build = "0.5.10"

[dev-dependencies]
ctor = "0.2"
ndarray = "0.16"
ndarray-rand = "0.15"
rand = "0.8"

[[test]]
name = "test_grammar_matcher"
required-features = ["hf_hub"]

[[test]]
name = "test_grammar_compiler"
required-features = ["hf_hub"]

[[test]]
name = "test_grammar"
required-features = ["hf_hub"]

[[test]]
name = "test_huggingface_hub"
required-features = ["hf_hub"]

[[test]]
name = "test_tokenizer_info"
required-features = ["hf_hub"]

[[test]]
name = "test_e2e"
required-features = ["hf_hub"]
